### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by fott1** [TwilioDevEd/clicktocall-node#12]
Is it ok if we use `client.makeCall` ?

or it should be changed to `client.calls.create` ?

**Comment by philnash** [comment]
It doesn't matter which you use 🙂 

`client.makeCall` is really just an alias to `client.calls.post` as [you can see in the `RestClient`](https://github.com/twilio/twilio-node/blob/48a13eb15b88ab982e1ae600cf13898da26ab260/lib/RestClient.js#L49).

`client.calls.post` is then generated by [this line](https://github.com/twilio/twilio-node/blob/master/lib/resources/Calls.js#L41) which also generates `client.calls.create` to also make the POST request to the Calls resource.

So, you can actually use any of `client.makeCall`, `client.calls.post` or `client.calls.create` to make a call. I only recommend that you pick one within your codebase and stick to it to avoid confusion.

**Comment by fott1** [comment]
Your answer was perfect. Thanks. 

One last question, i am facing an issue when trying to access the `request.body.*  ` variables. 
I use: 
```
app.use(bodyParser.urlencoded({
        extended: true
}));
```
But it seems that probably is a configuration issue. I am posting the body data required but inside my `app.post() ` those variables are always undefined. Does the order || sequence of middlewares plays any significant role here?

**Comment by fott1** [comment]
I figured out what happened. For any-one who might be facing the same issue. 

I had to set `app.use(bodyParser.json()); ` to support JSON-encoded bodies
and of course make the POST request using:` 'Content-Type': 'application/json'` 

Thank you for your help. @philnash
