### ISSUE TITLE
Getting Error : username is required on node app.js run

### ISSUE THREAD

**Issue by honeyonsys** [TwilioDevEd/clicktocall-node#15]
F:\laragon\www\twillio_starter\node_modules\twilio\lib\rest\Twilio.js:98
    throw new Error('username is required');
    ^

Error: username is required
    at new Twilio (F:\laragon\www\twillio_starter\node_modules\twilio\lib\rest\Twilio.js:98:11)
    at initializer (F:\laragon\www\twillio_starter\node_modules\twilio\lib\index.js:8:10)
    at Object.<anonymous> (F:\laragon\www\twillio_starter\routes\index.js:11:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by philnash** [comment]
Hey @honeyonsys, the missing username refers to your Account Sid (bad name, I know, but it can also be an API Key Sid).

Make sure you follow [the steps in the README under configuration](https://github.com/TwilioDevEd/clicktocall-node#configuration) and try again. 

Let me know if that helps.

**Comment by SORNVENGE** [comment]
![error](https://user-images.githubusercontent.com/43216195/46271216-bac33180-c575-11e8-8569-d69af0633d88.PNG)


i have error like that too but now not yet t o solve it so who can help me? thank you before your helping!

**Comment by philnash** [comment]
@SORNVENGE Few things here.

First and most importantly, _log in to your Twilio account and request a new auth token_. Your screenshot is showing the whole world how to access your account.

Secondly, you are trying to initialise the client with two environment variables, which I assume you have not set. Instead, your account sid and auth token are listed above as variables. I recommend you read up on [how to set environment variables](https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html) as that is more secure than saving them in your code. For a quick win, I would change the line where you initialise your client to this:

```
var client = require('twilio')(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN);
```

**Comment by ShourovRoy** [comment]
I have write all the codes according to the docs but it's still showing me "username is required"

**Comment by bld010** [comment]
Hi @ShourovRoy Have you copied the `.env.example` file to a `.env` file with your Twilio Account details filled in?

**Comment by carleii** [comment]
in cmd line do : npm install dotenv --save
